version: '3.9'

#
# Plex - 32400
# Transmission - 9091
# Sickchill - 8081
# Radar - 7878
#

secrets:
  openvpn_user:
    file: ./data/config/secrets/openvpn_user.cred
  openvpn_password:
    file: ./data/config/secrets/openvpn_password.cred
  plex_claim:
    file: ./data/config/secrets/plex_claim

x-name:
 - &NAME 'cinebox'
 - &NET 'cinebox_net'

x-template: &default-template
  environment:
    TZ: 'Europe/Amsterdam'
  restart: "unless-stopped"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"

networks:
  net: #external / internet
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.8.192/29
    driver_opts:
      com.docker.network.bridge.name: *NET

services:

  nginx:
    <<: *default-template
    image: nginx:stable-alpine
    container_name: nginx
    environment:
      - SERVERNAME=cinebox.koetsier.dev
    volumes:
      - "./data/config/etc/nginx/cinebox/:/usr/share/nginx/html:ro"
      - "./data/config/etc/nginx/templates:/etc/nginx/templates"
      - "./data/logs/nginx:/var/log/nginx"
    network_mode: "service:gluetun"
    depends_on:
      - "gluetun"


  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 80:80/tcp
      - 32400:32400/tcp
    volumes:
      - ./data/config/etc/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
        #openvpn
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - SERVER_REGIONS=Germany
      - HEALTH_VPN_DURATION_ADDITION=15s
      - UPDATER_PERIOD=24h
        #firewall
#     - FIREWALL_OUTBOUND_SUBNETS=<containersSubnet>,<multicast>, <dockerhostSubnet>
      - FIREWALL_DEBUG=off
        # DNS over TLS
      - DOT=on
      - DNS_KEEP_NAMESERVER=on
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
      - DOT_PROVIDERS=cloudflare #cloudflare,google,quad9,quadrant,cleanbrowsing
        # other
      - PUBLICIP_PERIOD=3h
      - PUBLICIP_API=ipinfo
      - TZ=Europe/Amsterdam
    secrets:
      - source: openvpn_user
      - source: openvpn_password
    networks:
      - net

  debug: #1234
    container_name: debug
    build: ./test
    network_mode: "service:gluetun"
    restart: "no"
    stdin_open: true
    tty: true
    profiles:
    - debug


  transmission: #9091
    <<: *default-template
    container_name: transmission
    image: linuxserver/transmission:latest
    network_mode: "service:gluetun"
    stdin_open: true
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "./data/config/etc/transmission:/config"
      - "./data/media/downloads:/downloads"


  radarr:  #7878
    <<: *default-template
    container_name: radarr
    image: "linuxserver/radarr:latest"
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    network_mode: "service:gluetun"
    stdin_open: true
    tty: true
    volumes:
      - "./data/config/etc/radarr:/config"
      - "./data/media/movies:/movies"
      - "./data/media/downloads:/downloads"


  plex: #32400
    <<: *default-template
    container_name: plex
    image: linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=/run/secrets/plex_claim #https://plex.tv/claim
    network_mode: "service:gluetun"
    stdin_open: true
    tty: true
    volumes:
      - "./data/config/etc/plex:/config"
      - "./data/media/series:/tv"
      - "./data/media/movies:/movies"
    secrets:
      - source: plex_claim
    profiles:
      - plex


  jackett:
    <<: *default-template
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true #optional 
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - "./data/config/etc/jacket:/config"
#      - "./data/media/watch:/downloads"

  emby:
    <<: *default-template
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/config/etc/emby:/config
      - ./data/media/series:/data/tvshows
      - ./data/media/movies:/data/movies
#      - /opt/vc/lib:/opt/vc/lib #optional
#    devices:
#      - /dev/dri:/dev/dri #optional
#      - /dev/vchiq:/dev/vchiq #optional
#      - /dev/video10:/dev/video10 #optional
#      - /dev/video11:/dev/video11 #optional
#      - /dev/video12:/dev/video12 #optional


  medusa:
    <<: *default-template
    image: lscr.io/linuxserver/medusa:latest
    container_name: medusa
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/config/etc/medusa:/config
      - ./data/media/downloads:/downloads
      - ./data/media/series:/tv
    restart: unless-stopped

